//*****************************************************************************
//*****************************************************************************
//  FILENAME:  Eingangsamp.h  ( PGA )
//  Version: 3.2, Updated on 2015/3/4 at 22:26:46
//  Generated by PSoC Designer 5.4.3191
//
//  DESCRIPTION:  PGA User Module C Language interface file.
//-----------------------------------------------------------------------------
//      Copyright (c) Cypress Semiconductor 2015. All Rights Reserved.
//*****************************************************************************
//*****************************************************************************
#ifndef Eingangsamp_INCLUDE
#define Eingangsamp_INCLUDE

#include <M8C.h>

//-------------------------------------------------
// Constants for Eingangsamp API's.
//-------------------------------------------------
#define Eingangsamp_OFF         0
#define Eingangsamp_LOWPOWER    1
#define Eingangsamp_MEDPOWER    2
#define Eingangsamp_HIGHPOWER   3

#define Eingangsamp_G48_0    0x0C
#define Eingangsamp_G24_0    0x1C

#define Eingangsamp_G16_0    0x08
#define Eingangsamp_G8_00    0x18
#define Eingangsamp_G5_33    0x28
#define Eingangsamp_G4_00    0x38
#define Eingangsamp_G3_20    0x48
#define Eingangsamp_G2_67    0x58
#define Eingangsamp_G2_27    0x68
#define Eingangsamp_G2_00    0x78
#define Eingangsamp_G1_78    0x88
#define Eingangsamp_G1_60    0x98
#define Eingangsamp_G1_46    0xA8
#define Eingangsamp_G1_33    0xB8
#define Eingangsamp_G1_23    0xC8
#define Eingangsamp_G1_14    0xD8
#define Eingangsamp_G1_06    0xE8
#define Eingangsamp_G1_00    0xF8
#define Eingangsamp_G0_93    0xE0
#define Eingangsamp_G0_87    0xD0
#define Eingangsamp_G0_81    0xC0
#define Eingangsamp_G0_75    0xB0
#define Eingangsamp_G0_68    0xA0
#define Eingangsamp_G0_62    0x90
#define Eingangsamp_G0_56    0x80
#define Eingangsamp_G0_50    0x70
#define Eingangsamp_G0_43    0x60
#define Eingangsamp_G0_37    0x50
#define Eingangsamp_G0_31    0x40
#define Eingangsamp_G0_25    0x30
#define Eingangsamp_G0_18    0x20
#define Eingangsamp_G0_12    0x10
#define Eingangsamp_G0_06    0x00

#define Eingangsamp_AGNDBUFAPI 0

#pragma fastcall16 Eingangsamp_Start
#pragma fastcall16 Eingangsamp_SetPower
#pragma fastcall16 Eingangsamp_SetGain
#pragma fastcall16 Eingangsamp_Stop

#if (Eingangsamp_AGNDBUFAPI)
#pragma fastcall16 Eingangsamp_EnableAGNDBuffer
#pragma fastcall16 Eingangsamp_DisableAGNDBuffer
#endif

//-------------------------------------------------
// Prototypes of the Eingangsamp API.
//-------------------------------------------------
extern void Eingangsamp_Start(BYTE bPowerSetting);     // Proxy class 2
extern void Eingangsamp_SetPower(BYTE bPowerSetting);  // Proxy class 2
extern void Eingangsamp_SetGain(BYTE bGainSetting);    // Proxy class 2
extern void Eingangsamp_Stop(void);                    // Proxy class 1

#if (Eingangsamp_AGNDBUFAPI)
extern void Eingangsamp_EnableAGNDBuffer(void);
extern void Eingangsamp_DisableAGNDBuffer(void);
#endif

//-------------------------------------------------
// Register Addresses for Eingangsamp
//-------------------------------------------------

#pragma ioport  Eingangsamp_GAIN_CR0:   0x075
BYTE            Eingangsamp_GAIN_CR0;
#pragma ioport  Eingangsamp_GAIN_CR1:   0x076
BYTE            Eingangsamp_GAIN_CR1;
#pragma ioport  Eingangsamp_GAIN_CR2:   0x077
BYTE            Eingangsamp_GAIN_CR2;
#pragma ioport  Eingangsamp_GAIN_CR3:   0x074
BYTE            Eingangsamp_GAIN_CR3;

#endif
// end of file Eingangsamp.h
