/******************************************************************************
*  Generated by PSoC Designer 5.4.3191
******************************************************************************/
// =============================================================================
// FILENAME: PSoCAPI.h
// 
// Copyright (c) Cypress Semiconductor 2013. All Rights Reserved.
// 
// NOTES:
// Do not modify this file. It is generated by PSoC Designer each time the
// generate application function is run. The values of the parameters in this
// file can be modified by changing the values of the global parameters in the
// device editor.
// 
// =============================================================================
 
#ifndef __PSOCAPI_H
#define __PSOCAPI_H

#include "PSoCGPIOINT.h"
#include "ADCINC_1.h"
#include "COMP_1.h"
#include "DAC8_1.h"
#include "E2PROM_1.h"
#include "Eingangsamp.h"
#include "HF_power.h"
#include "LCD_1.h"
#include "PGA_1.h"
#include "PTT.h"
#include "RefMux_1.h"
#include "Timer8_1.h"
#include "Timer8_2.h"
#include "Timer8_3.h"
#include "UART_1.h"
#include "UART_2.h"

#endif
