;  Generated by PSoC Designer 5.4.3191
;
; =============================================================================
; FILENAME: PSoCConfigTBL.asm
;  
; Copyright (c) Cypress Semiconductor 2013. All Rights Reserved.
;  
; NOTES:
; Do not modify this file. It is generated by PSoC Designer each time the
; generate application function is run. The values of the parameters in this
; file can be modified by changing the values of the global parameters in the
; device editor.
;  
; =============================================================================
 
include "m8c.inc"
;  Personalization tables 
export LoadConfigTBL_fmfunke_Bank1
export LoadConfigTBL_fmfunke_Bank0
export LoadConfigTBL_fmfunke_Ordered
AREA lit(rom, rel)
LoadConfigTBL_fmfunke_Bank0:
;  Instance name ADCINC_1, User Module ADCINC
;       Instance name ADCINC_1, Block Name ADC(ASC12)
	db		88h, 90h		;ADCINC_1_AtoDcr0(ASC12CR0)
	db		89h, 00h		;ADCINC_1_AtoDcr1(ASC12CR1)
	db		8ah, 60h		;ADCINC_1_AtoDcr2(ASC12CR2)
	db		8bh, f0h		;ADCINC_1_AtoDcr3(ASC12CR3)
;       Instance name ADCINC_1, Block Name PWM(DBB01)
	db		27h, 00h		;ADCINC_1_PWMcr0(DBB01CR0)
	db		25h, 00h		;ADCINC_1_PWMdr1(DBB01DR1)
	db		26h, 01h		;ADCINC_1_PWMdr2(DBB01DR2)
;  Instance name COMP_1, User Module COMP
;       Instance name COMP_1, Block Name COMP(ACB03)
	db		7dh, 8ah		;COMP_1_CR0(ACB03CR0)
	db		7eh, 61h		;COMP_1_CR1(ACB03CR1)
	db		7fh, 40h		;COMP_1_CR2(ACB03CR2)
	db		7ch, 00h		;COMP_1_CR3(ACB03CR3)
;  Instance name DAC8_1, User Module DAC8
;       Instance name DAC8_1, Block Name LSB(ASD20)
	db		90h, 80h		;DAC8_1_LSB_CR0(ASD20CR0)
	db		91h, 80h		;DAC8_1_LSB_CR1(ASD20CR1)
	db		92h, 20h		;DAC8_1_LSB_CR2(ASD20CR2)
	db		93h, 30h		;DAC8_1_LSB_CR3(ASD20CR3)
;       Instance name DAC8_1, Block Name MSB(ASC21)
	db		94h, a0h		;DAC8_1_MSB_CR0(ASC21CR0)
	db		95h, 41h		;DAC8_1_MSB_CR1(ASC21CR1)
	db		96h, 20h		;DAC8_1_MSB_CR2(ASC21CR2)
	db		97h, 34h		;DAC8_1_MSB_CR3(ASC21CR3)
;  Instance name E2PROM_1, User Module E2PROM
;  Instance name Eingangsamp, User Module PGA
;       Instance name Eingangsamp, Block Name GAIN(ACB01)
	db		75h, fdh		;Eingangsamp_GAIN_CR0(ACB01CR0)
	db		76h, a1h		;Eingangsamp_GAIN_CR1(ACB01CR1)
	db		77h, 20h		;Eingangsamp_GAIN_CR2(ACB01CR2)
	db		74h, 00h		;Eingangsamp_GAIN_CR3(ACB01CR3)
;  Instance name HF_power, User Module LED
;  Instance name LCD_1, User Module LCD
;  Instance name PGA_1, User Module PGA
;       Instance name PGA_1, Block Name GAIN(ACB02)
	db		79h, feh		;PGA_1_GAIN_CR0(ACB02CR0)
	db		7ah, 21h		;PGA_1_GAIN_CR1(ACB02CR1)
	db		7bh, 20h		;PGA_1_GAIN_CR2(ACB02CR2)
	db		78h, 00h		;PGA_1_GAIN_CR3(ACB02CR3)
;  Instance name PTT, User Module LED
;  Instance name RefMux_1, User Module RefMux
;       Instance name RefMux_1, Block Name REFMUX(ACB00)
	db		71h, 01h		;RefMux_1_REFMUX_CR0(ACB00CR0)
	db		72h, 09h		;RefMux_1_REFMUX_CR1(ACB00CR1)
	db		73h, 14h		;RefMux_1_REFMUX_CR2(ACB00CR2)
	db		70h, 00h		;RefMux_1_REFMUX_CR3(ACB00CR3)
;  Instance name Timer8_1, User Module Timer8
;       Instance name Timer8_1, Block Name TIMER8(DBB00)
	db		23h, 04h		;Timer8_1_CONTROL_REG(DBB00CR0)
	db		21h, 4eh		;Timer8_1_PERIOD_REG(DBB00DR1)
	db		22h, 27h		;Timer8_1_COMPARE_REG(DBB00DR2)
;  Instance name Timer8_2, User Module Timer8
;       Instance name Timer8_2, Block Name TIMER8(DBB11)
	db		37h, 04h		;Timer8_2_CONTROL_REG(DBB11CR0)
	db		35h, 1fh		;Timer8_2_PERIOD_REG(DBB11DR1)
	db		36h, 00h		;Timer8_2_COMPARE_REG(DBB11DR2)
;  Instance name Timer8_3, User Module Timer8
;       Instance name Timer8_3, Block Name TIMER8(DBB10)
	db		33h, 04h		;Timer8_3_CONTROL_REG(DBB10CR0)
	db		31h, 00h		;Timer8_3_PERIOD_REG(DBB10DR1)
	db		32h, 00h		;Timer8_3_COMPARE_REG(DBB10DR2)
;  Instance name UART_1, User Module UART
;       Instance name UART_1, Block Name RX(DCB03)
	db		2fh, 00h		;UART_1_RX_CONTROL_REG(DCB03CR0)
	db		2dh, 00h		;UART_1_(DCB03DR1)
	db		2eh, 00h		;UART_1_RX_BUFFER_REG (DCB03DR2)
;       Instance name UART_1, Block Name TX(DCB02)
	db		2bh, 00h		;UART_1_TX_CONTROL_REG(DCB02CR0)
	db		29h, 00h		;UART_1_TX_BUFFER_REG (DCB02DR1)
	db		2ah, 00h		;UART_1_(DCB02DR2)
;  Instance name UART_2, User Module UART
;       Instance name UART_2, Block Name RX(DCB13)
	db		3fh, 00h		;UART_2_RX_CONTROL_REG(DCB13CR0)
	db		3dh, 00h		;UART_2_(DCB13DR1)
	db		3eh, 00h		;UART_2_RX_BUFFER_REG (DCB13DR2)
;       Instance name UART_2, Block Name TX(DCB12)
	db		3bh, 00h		;UART_2_TX_CONTROL_REG(DCB12CR0)
	db		39h, 00h		;UART_2_TX_BUFFER_REG (DCB12DR1)
	db		3ah, 00h		;UART_2_(DCB12DR2)
;  Global Register values Bank 0
	db		60h, 3eh		; AnalogColumnInputSelect register (AMX_IN)
	db		66h, 00h		; AnalogComparatorControl1 register (CMP_CR1)
	db		63h, 17h		; AnalogReferenceControl register (ARF_CR)
	db		65h, 00h		; AnalogSyncControl register (ASY_CR)
	db		e6h, 04h		; DecimatorControl_0 register (DEC_CR0)
	db		e7h, 01h		; DecimatorControl_1 register (DEC_CR1)
	db		d6h, 00h		; I2CConfig register (I2CCFG)
	db		b0h, 00h		; Row_0_InputMux register (RDI0RI)
	db		b1h, 00h		; Row_0_InputSync register (RDI0SYN)
	db		b2h, 00h		; Row_0_LogicInputAMux register (RDI0IS)
	db		b3h, 33h		; Row_0_LogicSelect_0 register (RDI0LT0)
	db		b4h, 53h		; Row_0_LogicSelect_1 register (RDI0LT1)
	db		b5h, 00h		; Row_0_OutputDrive_0 register (RDI0SRO0)
	db		b6h, 20h		; Row_0_OutputDrive_1 register (RDI0SRO1)
	db		b8h, 42h		; Row_1_InputMux register (RDI1RI)
	db		b9h, 00h		; Row_1_InputSync register (RDI1SYN)
	db		bah, 00h		; Row_1_LogicInputAMux register (RDI1IS)
	db		bbh, 33h		; Row_1_LogicSelect_0 register (RDI1LT0)
	db		bch, 33h		; Row_1_LogicSelect_1 register (RDI1LT1)
	db		bdh, 00h		; Row_1_OutputDrive_0 register (RDI1SRO0)
	db		beh, 01h		; Row_1_OutputDrive_1 register (RDI1SRO1)
	db		ffh
LoadConfigTBL_fmfunke_Bank1:
;  Instance name ADCINC_1, User Module ADCINC
;       Instance name ADCINC_1, Block Name ADC(ASC12)
;       Instance name ADCINC_1, Block Name PWM(DBB01)
	db		24h, 31h		;ADCINC_1_PWMfn(DBB01FN)
	db		25h, 16h		;ADCINC_1_PWMsl(DBB01IN)
	db		26h, 40h		;ADCINC_1_PWMos(DBB01OU)
;  Instance name COMP_1, User Module COMP
;       Instance name COMP_1, Block Name COMP(ACB03)
;  Instance name DAC8_1, User Module DAC8
;       Instance name DAC8_1, Block Name LSB(ASD20)
;       Instance name DAC8_1, Block Name MSB(ASC21)
;  Instance name E2PROM_1, User Module E2PROM
;  Instance name Eingangsamp, User Module PGA
;       Instance name Eingangsamp, Block Name GAIN(ACB01)
;  Instance name HF_power, User Module LED
;  Instance name LCD_1, User Module LCD
;  Instance name PGA_1, User Module PGA
;       Instance name PGA_1, Block Name GAIN(ACB02)
;  Instance name PTT, User Module LED
;  Instance name RefMux_1, User Module RefMux
;       Instance name RefMux_1, Block Name REFMUX(ACB00)
;  Instance name Timer8_1, User Module Timer8
;       Instance name Timer8_1, Block Name TIMER8(DBB00)
	db		20h, 60h		;Timer8_1_FUNC_REG(DBB00FN)
	db		21h, 15h		;Timer8_1_INPUT_REG(DBB00IN)
	db		22h, 40h		;Timer8_1_OUTPUT_REG(DBB00OU)
;  Instance name Timer8_2, User Module Timer8
;       Instance name Timer8_2, Block Name TIMER8(DBB11)
	db		34h, 28h		;Timer8_2_FUNC_REG(DBB11FN)
	db		35h, 11h		;Timer8_2_INPUT_REG(DBB11IN)
	db		36h, 40h		;Timer8_2_OUTPUT_REG(DBB11OU)
;  Instance name Timer8_3, User Module Timer8
;       Instance name Timer8_3, Block Name TIMER8(DBB10)
	db		30h, 20h		;Timer8_3_FUNC_REG(DBB10FN)
	db		31h, 15h		;Timer8_3_INPUT_REG(DBB10IN)
	db		32h, 40h		;Timer8_3_OUTPUT_REG(DBB10OU)
;  Instance name UART_1, User Module UART
;       Instance name UART_1, Block Name RX(DCB03)
	db		2ch, 05h		;UART_1_RX_FUNC_REG   (DCB03FN)
	db		2dh, c2h		;UART_1_RX_INPUT_REG  (DCB03IN)
	db		2eh, 40h		;UART_1_RX_OUTPUT_REG (DCB03OU)
;       Instance name UART_1, Block Name TX(DCB02)
	db		28h, 0dh		;UART_1_TX_FUNC_REG   (DCB02FN)
	db		29h, 02h		;UART_1_TX_INPUT_REG  (DCB02IN)
	db		2ah, 44h		;UART_1_TX_OUTPUT_REG (DCB02OU)
;  Instance name UART_2, User Module UART
;       Instance name UART_2, Block Name RX(DCB13)
	db		3ch, 05h		;UART_2_RX_FUNC_REG   (DCB13FN)
	db		3dh, d2h		;UART_2_RX_INPUT_REG  (DCB13IN)
	db		3eh, 40h		;UART_2_RX_OUTPUT_REG (DCB13OU)
;       Instance name UART_2, Block Name TX(DCB12)
	db		38h, 1dh		;UART_2_TX_FUNC_REG   (DCB12FN)
	db		39h, 02h		;UART_2_TX_INPUT_REG  (DCB12IN)
	db		3ah, 46h		;UART_2_TX_OUTPUT_REG (DCB12OU)
;  Global Register values Bank 1
	db		61h, 0ch		; AnalogClockSelect1 register (CLK_CR1)
	db		69h, 00h		; AnalogClockSelect2 register (CLK_CR2)
	db		60h, 55h		; AnalogColumnClockSelect register (CLK_CR0)
	db		62h, 29h		; AnalogIOControl_0 register (ABF_CR0)
	db		67h, 33h		; AnalogLUTControl0 register (ALT_CR0)
	db		68h, 33h		; AnalogLUTControl1 register (ALT_CR1)
	db		63h, 00h		; AnalogModulatorControl_0 register (AMD_CR0)
	db		66h, 00h		; AnalogModulatorControl_1 register (AMD_CR1)
	db		d1h, 00h		; GlobalDigitalInterconnect_Drive_Even_Input register (GDI_E_IN)
	db		d3h, 00h		; GlobalDigitalInterconnect_Drive_Even_Output register (GDI_E_OU)
	db		d0h, 00h		; GlobalDigitalInterconnect_Drive_Odd_Input register (GDI_O_IN)
	db		d2h, 00h		; GlobalDigitalInterconnect_Drive_Odd_Output register (GDI_O_OU)
	db		e1h, 3fh		; OscillatorControl_1 register (OSC_CR1)
	db		e2h, 00h		; OscillatorControl_2 register (OSC_CR2)
	db		dfh, 09h		; OscillatorControl_3 register (OSC_CR3)
	db		deh, 02h		; OscillatorControl_4 register (OSC_CR4)
	db		ddh, 00h		; OscillatorGlobalBusEnableControl register (OSC_GO_EN)
	db		ffh
AREA psoc_config(rom, rel)
LoadConfigTBL_fmfunke_Ordered:
;  Ordered Global Register values
	M8C_SetBank0
	mov	reg[00h], 00h		; Port_0_Data register (PRT0DR)
	M8C_SetBank1
	mov	reg[00h], 04h		; Port_0_DriveMode_0 register (PRT0DM0)
	mov	reg[01h], fbh		; Port_0_DriveMode_1 register (PRT0DM1)
	M8C_SetBank0
	mov	reg[03h], f8h		; Port_0_DriveMode_2 register (PRT0DM2)
	mov	reg[02h], 07h		; Port_0_GlobalSelect register (PRT0GS)
	M8C_SetBank1
	mov	reg[02h], 00h		; Port_0_IntCtrl_0 register (PRT0IC0)
	mov	reg[03h], 00h		; Port_0_IntCtrl_1 register (PRT0IC1)
	M8C_SetBank0
	mov	reg[01h], 00h		; Port_0_IntEn register (PRT0IE)
	mov	reg[04h], e6h		; Port_1_Data register (PRT1DR)
	M8C_SetBank1
	mov	reg[04h], 06h		; Port_1_DriveMode_0 register (PRT1DM0)
	mov	reg[05h], ffh		; Port_1_DriveMode_1 register (PRT1DM1)
	M8C_SetBank0
	mov	reg[07h], 0ah		; Port_1_DriveMode_2 register (PRT1DM2)
	mov	reg[06h], 01h		; Port_1_GlobalSelect register (PRT1GS)
	M8C_SetBank1
	mov	reg[06h], a0h		; Port_1_IntCtrl_0 register (PRT1IC0)
	mov	reg[07h], 80h		; Port_1_IntCtrl_1 register (PRT1IC1)
	M8C_SetBank0
	mov	reg[05h], a0h		; Port_1_IntEn register (PRT1IE)
	mov	reg[08h], 00h		; Port_2_Data register (PRT2DR)
	M8C_SetBank1
	mov	reg[08h], ffh		; Port_2_DriveMode_0 register (PRT2DM0)
	mov	reg[09h], 00h		; Port_2_DriveMode_1 register (PRT2DM1)
	M8C_SetBank0
	mov	reg[0bh], 00h		; Port_2_DriveMode_2 register (PRT2DM2)
	mov	reg[0ah], 80h		; Port_2_GlobalSelect register (PRT2GS)
	M8C_SetBank1
	mov	reg[0ah], 00h		; Port_2_IntCtrl_0 register (PRT2IC0)
	mov	reg[0bh], 00h		; Port_2_IntCtrl_1 register (PRT2IC1)
	M8C_SetBank0
	mov	reg[09h], 00h		; Port_2_IntEn register (PRT2IE)
	mov	reg[0ch], 00h		; Port_3_Data register (PRT3DR)
	M8C_SetBank1
	mov	reg[0ch], 00h		; Port_3_DriveMode_0 register (PRT3DM0)
	mov	reg[0dh], 00h		; Port_3_DriveMode_1 register (PRT3DM1)
	M8C_SetBank0
	mov	reg[0fh], 00h		; Port_3_DriveMode_2 register (PRT3DM2)
	mov	reg[0eh], 00h		; Port_3_GlobalSelect register (PRT3GS)
	M8C_SetBank1
	mov	reg[0eh], 00h		; Port_3_IntCtrl_0 register (PRT3IC0)
	mov	reg[0fh], 00h		; Port_3_IntCtrl_1 register (PRT3IC1)
	M8C_SetBank0
	mov	reg[0dh], 00h		; Port_3_IntEn register (PRT3IE)
	mov	reg[10h], 00h		; Port_4_Data register (PRT4DR)
	M8C_SetBank1
	mov	reg[10h], 00h		; Port_4_DriveMode_0 register (PRT4DM0)
	mov	reg[11h], 00h		; Port_4_DriveMode_1 register (PRT4DM1)
	M8C_SetBank0
	mov	reg[13h], 00h		; Port_4_DriveMode_2 register (PRT4DM2)
	mov	reg[12h], 00h		; Port_4_GlobalSelect register (PRT4GS)
	M8C_SetBank1
	mov	reg[12h], 00h		; Port_4_IntCtrl_0 register (PRT4IC0)
	mov	reg[13h], 00h		; Port_4_IntCtrl_1 register (PRT4IC1)
	M8C_SetBank0
	mov	reg[11h], 00h		; Port_4_IntEn register (PRT4IE)
	mov	reg[14h], 00h		; Port_5_Data register (PRT5DR)
	M8C_SetBank1
	mov	reg[14h], 00h		; Port_5_DriveMode_0 register (PRT5DM0)
	mov	reg[15h], 00h		; Port_5_DriveMode_1 register (PRT5DM1)
	M8C_SetBank0
	mov	reg[17h], 00h		; Port_5_DriveMode_2 register (PRT5DM2)
	mov	reg[16h], 00h		; Port_5_GlobalSelect register (PRT5GS)
	M8C_SetBank1
	mov	reg[16h], 00h		; Port_5_IntCtrl_0 register (PRT5IC0)
	mov	reg[17h], 00h		; Port_5_IntCtrl_1 register (PRT5IC1)
	M8C_SetBank0
	mov	reg[15h], 00h		; Port_5_IntEn register (PRT5IE)
	M8C_SetBank0
	ret


; PSoC Configuration file trailer PsocConfig.asm
