//*****************************************************************************
//*****************************************************************************
//  FILENAME: PTT.h
//   Version: 2.00, Updated on 2015/3/4 at 22:26:37                                          
//  Generated by PSoC Designer 5.4.3191
//
//  DESCRIPTION: PTT User Module C Language interface file
//-----------------------------------------------------------------------------
//  Copyright (c) Cypress Semiconductor 2015. All Rights Reserved.
//*****************************************************************************
//*****************************************************************************
#ifndef PTT_INCLUDE
#define PTT_INCLUDE

#include <m8c.h>


/* Create pragmas to support proper argument and return value passing */
#pragma fastcall16  PTT_Stop
#pragma fastcall16  PTT_Start
#pragma fastcall16  PTT_On
#pragma fastcall16  PTT_Off
#pragma fastcall16  PTT_Switch
#pragma fastcall16  PTT_Invert
#pragma fastcall16  PTT_GetState


//-------------------------------------------------
// Constants for PTT API's.
//-------------------------------------------------
//
#define  PTT_ON   1
#define  PTT_OFF  0

//-------------------------------------------------
// Prototypes of the PTT API.
//-------------------------------------------------
extern void  PTT_Start(void);                                     
extern void  PTT_Stop(void);                                      
extern void  PTT_On(void);                                      
extern void  PTT_Off(void);                                      
extern void  PTT_Switch(BYTE bSwitch);
extern void  PTT_Invert(void);                                         
extern BYTE  PTT_GetState(void);                                         

//-------------------------------------------------
// Define global variables.                 
//-------------------------------------------------



#endif
