//*****************************************************************************
//*****************************************************************************
//  FILENAME:  RefMux_1.h
//  Version: 1.3, Updated on 2015/3/4 at 22:26:55
//  Generated by PSoC Designer 5.4.3191
//
//  DESCRIPTION:
//  DESCRIPTION: RefMux User Module C Language interface file.
//-----------------------------------------------------------------------------
//      Copyright (c) Cypress Semiconductor 2015. All Rights Reserved.
//*****************************************************************************
//*****************************************************************************
#ifndef RefMux_1_INCLUDE
#define RefMux_1_INCLUDE

#include <m8c.h>

//-------------------------------------------------
// Constants for RefMux_1 API's.
//-------------------------------------------------
#define RefMux_1_MUXOFF                0x00
#define RefMux_1_PMUXOUT               0x10
#define RefMux_1_AGND                  0x14
#define RefMux_1_REFLO                 0x18
#define RefMux_1_REFHI                 0x1C

#define RefMux_1_OFF                   0
#define RefMux_1_LOWPOWER              1
#define RefMux_1_MEDPOWER              2
#define RefMux_1_HIGHPOWER             3


#pragma fastcall16 RefMux_1_Start
#pragma fastcall16 RefMux_1_SetPower
#pragma fastcall16 RefMux_1_Stop
#pragma fastcall16 RefMux_1_RefSelect

//-------------------------------------------------
// Prototypes of the RefMux_1 API.
//-------------------------------------------------
extern void RefMux_1_Start(BYTE bPower);
extern void RefMux_1_SetPower(BYTE bPower);
extern void RefMux_1_Stop( void );
extern void RefMux_1_RefSelect(BYTE bRef);


//-------------------------------------------------
// Register Addresses for RefMux_1
//-------------------------------------------------

#pragma ioport  RefMux_1_REFMUX_CR0:    0x071
BYTE            RefMux_1_REFMUX_CR0;
#pragma ioport  RefMux_1_REFMUX_CR1:    0x072
BYTE            RefMux_1_REFMUX_CR1;
#pragma ioport  RefMux_1_REFMUX_CR2:    0x073
BYTE            RefMux_1_REFMUX_CR2;
#pragma ioport  RefMux_1_REFMUX_CR3:    0x070
BYTE            RefMux_1_REFMUX_CR3;

#endif
// end of file RefMux_1.
