;;*****************************************************************************
;;*****************************************************************************
;;  FILENAME: Timer8_2INT.asm
;;   Version: 2.70, Updated on 2015/3/4 at 22:27:48
;;  Generated by PSoC Designer 5.4.3191
;;
;;  DESCRIPTION: Timer8 Interrupt Service Routine
;;-----------------------------------------------------------------------------
;;  Copyright (c) Cypress Semiconductor 2015. All Rights Reserved.
;;*****************************************************************************
;;*****************************************************************************

include "m8c.inc"
include "memory.inc"
include "Timer8_2.inc"


;-----------------------------------------------
;  Global Symbols
;-----------------------------------------------
export  _Timer8_2_ISR


AREA InterruptRAM (RAM,REL,CON)

;@PSoC_UserCode_INIT@ (Do not change this line.)
;---------------------------------------------------
; Insert your custom declarations below this banner
;---------------------------------------------------

;------------------------
; Includes
;------------------------

	
;------------------------
;  Constant Definitions
;------------------------


;------------------------
; Variable Allocation
;------------------------


;---------------------------------------------------
; Insert your custom declarations above this banner
;---------------------------------------------------
;@PSoC_UserCode_END@ (Do not change this line.)


AREA UserModules (ROM, REL)

;-----------------------------------------------------------------------------
;  FUNCTION NAME: _Timer8_2_ISR
;
;  DESCRIPTION: Unless modified, this implements only a null handler stub.
;
;-----------------------------------------------------------------------------
;

_Timer8_2_ISR:

   ;@PSoC_UserCode_BODY@ (Do not change this line.)
   ;---------------------------------------------------
   ; Insert your custom assembly code below this banner
   ;---------------------------------------------------
   ;   NOTE: interrupt service routines must preserve
   ;   the values of the A and X CPU registers.
   
   ;---------------------------------------------------
   ; Insert your custom assembly code above this banner
   ;---------------------------------------------------
   							push       a
                            push       x
							lcall      Timer8_2_DisableInt
							mov        a,reg[PRT1DR]
                            and        a,1  
			     			asl        [_bit_buffer]
   							add        [_bit_buffer],a
							inc        [_bit_counter]
							cmp        [_bit_counter],8
							jnz        timerisr_ende
							and        [_bit_counter],0
							cmp        [_bit_buffer],0x7e
							jz         flagready
							and        [_bit_buffer],0
							jmp        timerisr_ende
	flagready:              
	                        mov        a,reg[PRT1DR]
                            and        a,1  
			     			asl        [_bit_buffer]
   							add        [_bit_buffer],a
							inc        [_bit_counter]
							cmp        [_bit_counter],8
							jnz        flagready
	                        mov        a,1
	                        mov        x,0
							lcall      LCD_1_Position
							mov        a,[_bit_buffer]
							lcall      LCD_1_PrHexByte
							and        [_bit_buffer],0
	timerisr_ende:			lcall      Timer8_2_EnableInt
							pop        x
							pop        a
							
   ;---------------------------------------------------
   ; Insert a lcall to a C function below this banner
   ; and un-comment the lines between these banners
   ;---------------------------------------------------
   
   ;PRESERVE_CPU_CONTEXT
   ;lcall _My_C_Function
   ;RESTORE_CPU_CONTEXT
   
   ;---------------------------------------------------
   ; Insert a lcall to a C function above this banner
   ; and un-comment the lines between these banners
   ;---------------------------------------------------
   ;@PSoC_UserCode_END@ (Do not change this line.)

   reti


; end of file Timer8_2INT.asm
