;  Generated by PSoC Designer 5.4.3191
;
;;*****************************************************************************
;;*****************************************************************************
;;  FILENAME: PSoCGPIOINT.asm
;;   Version: 2.0.0.20, Updated on 2003/07/17 at 12:10:35
;;  @PSOC_VERSION
;;
;;  DESCRIPTION: PSoC GPIO Interrupt Service Routine
;;-----------------------------------------------------------------------------
;;  Copyright (c) Cypress Semiconductor 2015. All Rights Reserved.
;;*****************************************************************************
;;*****************************************************************************

include "m8c.inc"
include "PSoCGPIOINT.inc"

;-----------------------------------------------
;  Global Symbols
;-----------------------------------------------
export   PSoC_GPIO_ISR


;-----------------------------------------------
;  Constant Definitions
;-----------------------------------------------


;-----------------------------------------------
; Variable Allocation
;-----------------------------------------------
	

;@PSoC_UserCode_INIT@ (Do not change this line.)
;---------------------------------------------------
; Insert your custom declarations below this banner
;---------------------------------------------------
  
;---------------------------------------------------
; Insert your custom declarations above this banner
;---------------------------------------------------
;@PSoC_UserCode_END@ (Do not change this line.)


;-----------------------------------------------------------------------------
;  FUNCTION NAME: PSoC_GPIO_ISR
;
;  DESCRIPTION: Unless modified, this implements only a null handler stub.
;
;-----------------------------------------------------------------------------
;
PSoC_GPIO_ISR:


   ;@PSoC_UserCode_BODY@ (Do not change this line.)
   ;---------------------------------------------------
   ; Insert your custom code below this banner
   ;---------------------------------------------------
  
   push    a 
   push    x
   M8C_DisableIntMask INT_MSK0, INT_MSK0_GPIO
   ;mov    a,reg[PRT0DR]
   ;and    a,24
   ;cmp    a,[lastPrt0]
   ;jnz     Lautstaerke
   tst    reg[PRT1DR],0x20
   jz       l1
   mov     a,reg[PRT1DR]
   and     a,192
   cmp     a,[lastPrt1]
   jz      isrende
   mov     [lastPrt1],a
   cmp     a,0x40
   jz      links   
   cmp     a,0
   jnz     isrende
   mov    [_direction],128
   jmp    isrende
links:
    mov   [_direction],129   
	jmp    isrende
l1:  
   or     [_TXstatus],16
   lcall  _Print_Frequenz
   lcall   w3
   lcall  PTT_Invert
   tst    reg[PRT1DR],0x20
   jz     l3
   or     [_TXstatus],32
   jmp    isrende
l3: 
   mov    a,3
   lcall Eingangsamp_Start
l2:M8C_ClearWDT
  ; lcall  _warte1ms
  ; tst    reg[PRT1DR],0x20
  ; jz    l2    
  ; lcall Eingangsamp_Stop
l9:   
  ; lcall PTT_Invert 
  ; and    [_TXstatus],0xef
  ; lcall   _Print_Frequenz
   mov    [_direction],0
   jmp    isrende
;Lautstaerke:
   ;mov     [lastPrt0],a
   ;cmp     a,0
   ;jz       l4
   ;cmp      a,0x10
   ;jnz     isrende
   ;cmp     [_volume],1
   ;jz      isrende
   ;dec     [_volume]
   ;lcall   _kommando_setvol
   ;jmp isrende
l4: 
   cmp     [_volume],8
   jz      isrende
   inc     [_volume]
   lcall   _kommando_setvol

isrende:
   and     reg[INT_CLR0],223
   
   
   
   M8C_EnableIntMask INT_MSK0,INT_MSK0_GPIO
   pop  x
   pop  a
   
   ;---------------------------------------------------
   ; Insert your custom code above this banner
   ;---------------------------------------------------
   ;@PSoC_UserCode_END@ (Do not change this line.)

   reti


; end of file PSoCGPIOINT.asm
