//*****************************************************************************
//*****************************************************************************
//  FILENAME: Timer8_3.h
//   Version: 2.70, Updated on 2015/3/4 at 22:27:48
//  Generated by PSoC Designer 5.4.3191
//
//  DESCRIPTION: Timer8 User Module C Language interface file
//-----------------------------------------------------------------------------
//  Copyright (c) Cypress Semiconductor 2015. All Rights Reserved.
//*****************************************************************************
//*****************************************************************************
#ifndef Timer8_3_INCLUDE
#define Timer8_3_INCLUDE

#include <m8c.h>

#pragma fastcall16 Timer8_3_EnableInt                 //                 Proxy 1
#pragma fastcall16 Timer8_3_DisableInt                //                 Proxy 1
#pragma fastcall16 Timer8_3_Start                     //                 Proxy 1
#pragma fastcall16 Timer8_3_Stop                      //                 Proxy 1
#pragma fastcall16 Timer8_3_bReadTimer                // Read  DR0       Proxy 1
#pragma fastcall16 Timer8_3_bReadTimerSaveCV          // Read  DR0       Proxy 2
#pragma fastcall16 Timer8_3_WritePeriod               // Write DR1       Proxy 1
#pragma fastcall16 Timer8_3_bReadCompareValue         // Read  DR2       Proxy 1
#pragma fastcall16 Timer8_3_WriteCompareValue         // Write DR2       Proxy 1

// The following symbols are deprecated.
// They may be omitted in future releases
//
#pragma fastcall16 bTimer8_3_ReadCounter              // Read  DR0 "Obsolete"
#pragma fastcall16 bTimer8_3_CaptureCounter           // Read  DR0 "Obsolete"
#pragma fastcall16 bTimer8_3_ReadTimer                // Read  DR0 (Deprecated)
#pragma fastcall16 bTimer8_3_ReadTimerSaveCV          // Read  DR0 (Deprecated)
#pragma fastcall16 bTimer8_3_ReadCompareValue         // Read  DR2 (Deprecated)


//-------------------------------------------------
// Prototypes of the Timer8_3 API.
//-------------------------------------------------

extern void Timer8_3_EnableInt(void);
extern void Timer8_3_DisableInt(void);
extern void Timer8_3_Start(void);
extern void Timer8_3_Stop(void);
extern BYTE Timer8_3_bReadTimer(void);
extern BYTE Timer8_3_bReadTimerSaveCV(void);
extern void Timer8_3_WritePeriod(BYTE bPeriod);
extern BYTE Timer8_3_bReadCompareValue(void);
extern void Timer8_3_WriteCompareValue(BYTE bCompareValue);

// The following functions are deprecated.
// They may be omitted in future releases
//
extern BYTE bTimer8_3_ReadCompareValue(void);       // Deprecated
extern BYTE bTimer8_3_ReadTimerSaveCV(void);        // Deprecated
extern BYTE bTimer8_3_ReadCounter(void);            // Obsolete
extern BYTE bTimer8_3_ReadTimer(void);              // Deprecated
extern BYTE bTimer8_3_CaptureCounter(void);         // Obsolete


//--------------------------------------------------
// Constants for Timer8_3 API's.
//--------------------------------------------------

#define Timer8_3_CONTROL_REG_START_BIT         ( 0x01 )
#define Timer8_3_INT_REG_ADDR                  ( 0x0e1 )
#define Timer8_3_INT_MASK                      ( 0x10 )


//--------------------------------------------------
// Constants for Timer8_3 user defined values
//--------------------------------------------------

#define Timer8_3_PERIOD                        ( 0x00 )
#define Timer8_3_COMPARE_VALUE                 ( 0x00 )


//-------------------------------------------------
// Register Addresses for Timer8_3
//-------------------------------------------------

#pragma ioport  Timer8_3_COUNTER_REG:   0x030              //DR0 Count register
BYTE            Timer8_3_COUNTER_REG;
#pragma ioport  Timer8_3_PERIOD_REG:    0x031              //DR1 Period register
BYTE            Timer8_3_PERIOD_REG;
#pragma ioport  Timer8_3_COMPARE_REG:   0x032              //DR2 Compare register
BYTE            Timer8_3_COMPARE_REG;
#pragma ioport  Timer8_3_CONTROL_REG:   0x033              //Control register
BYTE            Timer8_3_CONTROL_REG;
#pragma ioport  Timer8_3_FUNC_REG:  0x130                  //Function register
BYTE            Timer8_3_FUNC_REG;
#pragma ioport  Timer8_3_INPUT_REG: 0x131                  //Input register
BYTE            Timer8_3_INPUT_REG;
#pragma ioport  Timer8_3_OUTPUT_REG:    0x132              //Output register
BYTE            Timer8_3_OUTPUT_REG;
#pragma ioport  Timer8_3_INT_REG:       0x0e1              //Interrupt Mask Register
BYTE            Timer8_3_INT_REG;


//-------------------------------------------------
// Timer8_3 Macro 'Functions'
//-------------------------------------------------

#define Timer8_3_Start_M \
   ( Timer8_3_CONTROL_REG |=  Timer8_3_CONTROL_REG_START_BIT )

#define Timer8_3_Stop_M  \
   ( Timer8_3_CONTROL_REG &= ~Timer8_3_CONTROL_REG_START_BIT )

#define Timer8_3_EnableInt_M   \
   M8C_EnableIntMask(  Timer8_3_INT_REG, Timer8_3_INT_MASK )

#define Timer8_3_DisableInt_M  \
   M8C_DisableIntMask( Timer8_3_INT_REG, Timer8_3_INT_MASK )

#endif
// end of file Timer8_3.h
