PROJNAME=fmfunke2
DEVICE=CY8C27443B
BASEDEVICE=CY8C27000B
PROJPATH=F:/PSOCDE~1.4PR/fmfunke2/fmfunke2
PSOCDIR=D:/PROGRA~1/cypress/PSOCDE~1/5.4/Common/CYPRES~1
INCLUDE_PATH=D:/PROGRA~1/cypress/PSOCDE~1/5.4/Common/CYPRES~1/tools/include/CY8C27~1
CSRCS= main.c
LIBCSRCS=
STDCSRCS=
ASMSRCS= aprs.asm kommando.asm
LIBASMSRCS= adcinc_1.asm adcinc_1int.asm comp_1.asm comp_1int.asm dac8_1.asm e2prom_1.asm eingangsamp.asm hf_power.asm lcd_1.asm pga_1.asm psocconfig.asm psocconfigtbl.asm psocgpioint.asm ptt.asm refmux_1.asm timer8_1.asm timer8_1int.asm timer8_2.asm timer8_2int.asm timer8_3.asm timer8_3int.asm uart_1.asm uart_1int.asm uart_1plus.asm uart_2.asm uart_2int.asm uart_2plus.asm
STDASMSRCS=
OBJECT_SOURCES= aprs.asm kommando.asm main.c
FILLVALUE=0x30
LASTROM=0x3fff
LASTRAM=0xff
CODECOMPRESSOR=
MORE_CFLAGS=-Wf-nomac -Wf-Osize 
RELSTART=0x150
INC_PATH=
CDEFINES=
LIBS=
UMLIBS=
LIB_PATH=
ENABLE_ALIGN_SHIFT=0
LMM=
SYS_INC_CONTENTS:=SYSTEM_STACK_PAGE:_equ_0 SYSTEM_STACK_BASE_ADDR:_equ_0h SYSTEM_LARGE_MEMORY_MODEL:_equ_0 SYSTEM_SMALL_MEMORY_MODEL:_equ_1 IMAGECRAFT:_equ_1 HITECH:_equ_2 TOOLCHAIN:_equ_IMAGECRAFT 
SYSTEM_TOOLS=1
CSFLOW=
CONFIG_NAMES=fmfunke 
